version: 1.5.0.{build}

image: Visual Studio 2019

before_build:
- cmd: dotnet restore

build:
  verbosity: minimal

deploy:
- provider: NuGet
  api_key:
    secure: F9stGuIbUQoboJuAGMkMUULJMKhuR546Cd5vAZhToh2yoNuOF6z2E8flGI0b2fET
